// <auto-generated />
using TabCreator.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace TabCreator.Migrations
{
    [DbContext(typeof(TabCreatorContext))]
    [Migration("20240422185748_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TabCreator.Models.Chords", b =>
                {
                    b.Property<int>("ChordsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ChordsId"));

                    b.Property<string>("UserChord")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("ChordsId");

                    b.HasIndex("UserId");

                    b.ToTable("Chords");
                });

            modelBuilder.Entity("TabCreator.Models.Sheet", b =>
                {
                    b.Property<int>("SheetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SheetId"));

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("UserSheet")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SheetId");

                    b.HasIndex("UserId");

                    b.ToTable("Sheets");
                });

            modelBuilder.Entity("TabCreator.Models.Tablature", b =>
                {
                    b.Property<int>("TablatureId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TablatureId"));

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("UserTab")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TablatureId");

                    b.HasIndex("UserId");

                    b.ToTable("Tablatures");
                });

            modelBuilder.Entity("TabCreator.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("TabCreator.Models.Chords", b =>
                {
                    b.HasOne("TabCreator.Models.User", "User")
                        .WithMany("Chords")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TabCreator.Models.Sheet", b =>
                {
                    b.HasOne("TabCreator.Models.User", "User")
                        .WithMany("Sheet")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TabCreator.Models.Tablature", b =>
                {
                    b.HasOne("TabCreator.Models.User", "User")
                        .WithMany("Tablatures")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TabCreator.Models.User", b =>
                {
                    b.Navigation("Chords");

                    b.Navigation("Sheet");

                    b.Navigation("Tablatures");
                });
#pragma warning restore 612, 618
        }
    }
}
